// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"stream-video/pkg/api"
	"stream-video/pkg/api/service"
	"stream-video/pkg/config"
	"stream-video/pkg/db"
	"stream-video/pkg/repo"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.InitDB(c)
	if err != nil {
		return nil, err
	}
	videoRepo := repo.NewVideoRepo(gormDB)
	videoServiceServer := service.NewVideServer(videoRepo)
	server, err := api.NewGrpcServe(c, videoServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
